# Generated by Django 3.1.3 on 2020-12-03 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9}$')]),
        ),
    ]
