# Generated by Django 3.1.3 on 2020-12-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='default/usr_img.png', upload_to='user_img'),
        ),
    ]
