# Generated by Django 3.1.3 on 2020-11-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='featured',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
