# Generated by Django 3.1.3 on 2020-11-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0002_furniture_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='featured',
            field=models.BooleanField(default=False, max_length=4, null=True),
        ),
    ]
